// Generated by LiveScript 1.3.0
(function(){
  var http, srv;
  http = require('http');
  srv = http.createServer(function(req, res){
    res.write('test123');
    return res.end();
  });
  srv.listen(8888);
}).call(this);
